modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "LGPL"

[[mods]]
modId = "maxs_pvp_enhancements"
version = "${version}"
displayName = "Max's PvP Enhancements"
authors = "github.com/minMaximilian"
description = '''
Max's PvP Enhancements, set to make PvP as an event to look forwards to and reduce sadness after destruction.
'''
#logoFile = ""

[[dependencies.maxs_pvp_enhancements]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.maxs_pvp_enhancements]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"
